[package]
name = "lvl_0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }
quad-url = "0.1.1"

